### ISSUE TITLE
Other webui templates

### ISSUE THREAD

**Issue by zoraksss** [tetreum/amule-docker#4]
Hi again, sorry if I bother...

just to ask, there is anyway i could use another webui template?

I'd like to be able to use this skin:

https://github.com/elbowz/mobileMule

Maybe an option would be to be able to set a path to a custom skin for web templates and later define an environment variable with the desired one?

I don't know much about docker nor amule internals,sure you know better...

**Comment by tetreum** [comment]
uf i don't think it would be easy as  just setting an option. Because you need to download that template, unzip it in themes folder and then point amule to use it. Right now the listed option in docker is to change at which template it points, but just between those 2 available (default & the one that i download & unzip)

**Comment by zoraksss** [comment]
Ok, understood :) I just wanted to ask, maybe it was easy

**Comment by tetreum** [comment]
@zoraksss if you still wanna try that template, you can always do:
1. Run the following commands
```
sudo docker exec -it amule bash
cd /usr/share/amule/webserver
wget https://github.com/elbowz/mobileMule/releases/download/v3.3.0b/mobileMule-v3.3.0b-standard-version.tar.gz
tar -xf mobileMule-v3.3.0b-standard-version.tar.gz
rm -rf mobileMule/.git mobileMule-v3.3.0b-standard-version.tar.gz
mv AmuleWebUI-Reloaded/ AmuleWebUI-Reloaded2/
mv mobileMule/ AmuleWebUI-Reloaded
exit
```
2. Done

**Comment by zoraksss** [comment]
wow, thanks.

I was going to look how to do it somehow but you made my life a lot easier :)
